### ISSUE TITLE
Use the Point class throughout rather than an array of integers

### ISSUE THREAD

**Issue by wwiowac** [wwiowac/warehouse-project-a6#13]

**Comment by gwhite4** [comment]
I was thinking of how to accomplish that, I will take a stab at it tomorrow. The Robot class will have to  account for that as well.

**Comment by jroschen** [comment]
Can you be a bit more specific? Are you saying using the Point class for X,Y coordinates on the floor?

**Comment by jroschen** [comment]
#17 Should take care of this
